apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: rednorte
  labels:
    app: auth-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: gonzalo25u/rednorte-auth-service:${IMAGE_TAG}
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: rednorte-config
        - secretRef:
            name: rednorte-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: rednorte
spec:
  selector:
    app: auth-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP