apiVersion: v1
kind: ConfigMap
metadata:
  name: rednorte-config
  namespace: rednorte
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "rednorte"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  EUREKA_URL: "http://eureka-server-service:8761/eureka/"
  GATEWAY_URL: "http://gateway-service:8082"
  SUPABASE_URL: "https://pfprycndvkdxuzvgjqol.supabase.co"