apiVersion: v1
kind: Secret
metadata:
  name: rednorte-secrets
  namespace: rednorte
type: Opaque
stringData:
  DB_USERNAME: "REEMPLAZAR"
  DB_PASSWORD: "REEMPLAZAR"
  JWT_SECRET: "REEMPLAZAR"
  SUPABASE_ANON_KEY: "REEMPLAZAR"
  SUPABASE_SERVICE_KEY: "REEMPLAZAR"
  RABBITMQ_PASS: "guest"