apiVersion: v1
kind: Secret
metadata:
  name: rednorte-secrets
  namespace: rednorte
type: Opaque
stringData:
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_KEY: "${SUPABASE_SERVICE_KEY}"
  RABBITMQ_PASS: "guest"